### ISSUE TITLE
Software engineer junior

### ISSUE THREAD

**Issue by domix** [CirculoSiete/job-offerings#1]
# Descripción

Estamos buscando un apasionado ingeniero para diseñar, desarrollar y desplegar soluciones. El candidato será capaz de construir software de alta calidad, innovador, de alto rendimiento, en cumplimiento con las normas de codificación y del diseño técnico. Las responsabilidades del ingeniero de software incluirán desarrollo, escritura de código, automatización de pruebas y documentación de la funcionalidad.

## Responsabilidades

* Participar en el ciclo de vida completo de los proyectos
* Escribir código bien diseñado, testable y eficiente
* Producir especificaciones y determinar la viabilidad operativa
* Integrar componentes en un sistema de software completamente funcional
* Desarrollar planes de verificación de software y procedimientos de aseguramiento de calidad
* Documentar y mantener la funcionalidad del software
* Diseñar e implementar herramientas, procesos y métricas de software
* Servir como experto en la materia
* Cumplir con los planes del proyecto y los estándares de la industria
* Capacitar a usuarios operativos y de negocio

## Requerimientos mínimos

* Al menos un año de experiencia desarrollando software.
* Saber programar en algún ~dialecto~ lenguaje de las familias de C/C++
* Viva en el area metropolitana de la Ciudad de México
* Sin miedo a aprender

## Te ofrecemos

* Capacitación y coaching para el on-boarding de los proyectos
* **Sueldo** a evaluar según experiencia con posibilidades de crecimiento, el rango disponible para negociar es de **15,000 a 20,000 pesos bruto**.
* **Vacaciones**:

| Días   |      Años laborados      |
|:----------:|:-------------:|
| 6 |  1 |
| 8 |    2  |
| 10 | 3 |
| 12 |  4 |
| 14 |    5  |
| 15 | 6 en adelante |
* **Tiempo libre pagado**: **5 días por año** pagados por la empresa para tomarlos libres previa programación, no pueden ser usados de forma consecutiva. No son acumulables al término del año. 
* **Prima Vacacional**: 20% del día disfrutado de vacaciones.
* **Aguinaldo**: **15 días** por año completo
* Prestaciones de ley
* **Bono**: Cada seis meses se hace una evaluación para obtener **15 días** de sueldo.
* **5 días al año para asistir a conferencias**: La empresa paga estos días al empleado para que asista, los costos de las conferencias son cubiertos por el empleado. No son acumulables al término del año. 
* **Libros**: **500 USD** de presupuesto anual para libros, el empleado elige los libros y el ritmo para gastarlos. No es acumulable al término del año.

### Incentivo adicional condicionado. 

A partir del primer año cumplido, se hará una evaluación adicional, para determinar si se puede obtener el incentivo:

* La empresa cubre los costos de entrada, boletos y viáticos de la asistencia a una conferencia o curso nacional o internacional. Después de 5 años la empresa cubre la entrada a 2 conferencias o cursos.

# Contacto

Los interesados por favor enviar CV a Domingo Suarez Torres  <domingo@circulosiete.com>, si tienen alguna duda no duden en escribir también.

**Comment by cogitovsmachina** [comment]
👍
PS: ¿Te interesa que te comparta algunos leads de nuestra red del DevF?

**Comment by domix** [comment]
Estaría muy bien, espero a alguien le interese, muchas gracias @nrike

**Comment by domix** [comment]
@kanolato on board!
